name: Type Check

on:
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
    paths-ignore:
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: true
      matrix:
        command:
          - check:root
          - ws:type-check
          - ws:lint:fix
          - ws:test
          - ws:test:cov

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Fetch main
        run: git fetch origin main

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Cache Node.js modules
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ matrix.command }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-
            ${{ runner.OS }}-

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: 'package.json'
          registry-url: https://npm.pkg.github.com/
          scope: '@noshiro-pf'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright Browsers
        if: matrix.command == 'ws:test:cov'
        run: pnpm exec playwright install chromium

      # NOTE: To include this workflow in the branch protection rule status check,
      # skip each steps instead of skipping the entire workflow with paths-ignore.
      - name: Check diff
        id: check_diff_type
        run: pnpm exec check-should-run-type-checks

      - name: Build all packages
        run: pnpm run ws:build

      - name: Run "${{ matrix.command }}"
        if: steps.check_diff_type.outputs.should_run == 'true'
        run: pnpm run ${{ matrix.command }}

      - name: Check if there is no file diff
        run: pnpm exec assert-repo-is-clean

      - name: Upload coverage reports to Codecov
        if: steps.check_diff_type.outputs.should_run == 'true' && matrix.command == 'ws:test:cov'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
